# Generated by Django 2.0 on 2020-04-16 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='昵称')),
                ('sex', models.CharField(blank=True, choices=[('---', '---'), ('男', '男'), ('女', '女'), ('保密', '保密')], max_length=10, verbose_name='性别')),
                ('telephone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('user_logo', models.ImageField(null=True, upload_to='user', verbose_name='头像')),
                ('qq_number', models.CharField(blank=True, max_length=20, verbose_name='QQ号')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('school', models.CharField(blank=True, max_length=20, verbose_name='学校')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL, verbose_name='用户名称')),
            ],
        ),
    ]
