# Generated by Django 2.0 on 2020-04-24 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likecount',
            options={'verbose_name_plural': '喜欢计数'},
        ),
        migrations.AlterModelOptions(
            name='likerecord',
            options={'verbose_name_plural': '喜欢记录'},
        ),
        migrations.AlterField(
            model_name='likecount',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='喜欢对象模型'),
        ),
        migrations.AlterField(
            model_name='likecount',
            name='liked_num',
            field=models.IntegerField(default=0, verbose_name='喜欢数量'),
        ),
        migrations.AlterField(
            model_name='likecount',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='模型id'),
        ),
        migrations.AlterField(
            model_name='likerecord',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='喜欢对象模型'),
        ),
        migrations.AlterField(
            model_name='likerecord',
            name='liked_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='喜欢时间'),
        ),
        migrations.AlterField(
            model_name='likerecord',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='模型id'),
        ),
        migrations.AlterField(
            model_name='likerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='喜欢用户'),
        ),
    ]
