# Generated by Django 2.0 on 2020-04-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userextension', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextension',
            options={'verbose_name_plural': '拓展用户'},
        ),
    ]
