# Generated by Django 2.0 on 2020-04-24 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoalbum',
            options={'ordering': ['-create_time'], 'verbose_name_plural': '相册'},
        ),
        migrations.AlterModelOptions(
            name='photoalbumtype',
            options={'verbose_name_plural': '照片类型'},
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='brief_introduction',
            field=models.CharField(max_length=100, verbose_name='简单介绍'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='photo_img',
            field=models.ImageField(null=True, upload_to='photo', verbose_name='相册照片'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='photo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.PhotoAlbumType', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='photoalbumtype',
            name='type_name',
            field=models.CharField(max_length=15, verbose_name='照片类型'),
        ),
    ]
